service: run-app-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    platform: node
    target: node20

functions:
  api:
    handler: src/lambda.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

package:
  patterns:
    - "!node_modules/**"
